- hosts: master_node
  tasks:
  - name: copy deployment file to kubernetes master
    copy:
      src: deploy/k8s/
      dest: /root/
  - name: delete the previous of kubernetes objects
    command: kubectl delete -f /root/
  - name: Create a Deployment by reading the definition from a local file
    command: kubectl apply -f /root/