apiVersion: v1
kind: Service
metadata:
  name: book-my-show-service
  labels:
    name: book-my-show-service
    app: book-my-show-app
spec:
  type: LoadBalancer
  ports:
   - port: 80
     targetPort: 3000
  selector:
    name: book-my-show-app-pod
    app: book-my-show-app