apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: book-my-show-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: book-my-show-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: book-my-show-app
    spec:
      containers:
        - name: postgres
          image: postgres:9.4
          resources:
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432