default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: book-my-show_development

test:
  <<: *default
  database: book-my-show_test

production:
  <<: *default
  database: book-my-show_production
  username: postgres
  password: <%= ENV['BOOK-MY-SHOW_DATABASE_PASSWORD'] %>
