default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: book-my-show_development

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  <<: *default
  host: db
  database: book-my-show_production
  username: postgres
  password: <%= ENV['BOOK_MY_SHOW_DATABASE_PASSWORD'] %>
